public enum Menu {
    INITIAL_MENU, VILLAGE_MENU, MINE_MENU,
    STORAGE_MENU, STORAGE_INFO_MENU, MINE_INFO_MENU,
    DEFENSIVE_WEAPON_MENU, DEFENSIVE_WEAPON_INFO_MENU, UPGRADE_MENU, TOWN_HALL_MENU, TOWN_HALL_INFO_MENU,
    AVAILABLE_BUILDING_MENU, CONSTRUCTION_SOLDIER_WINDOW,
    BARRACK_MENU, BARRACK_INFO_MENU, LOAD_MAP_WINDOW,
    MAP_MENU, ATTACK_MAP_WINDOW, PUT_SOLDIERS_ON_MAP_WINDOW,
    REAL_GAME_SPACE, CAMP_MENU, CAMP_INFO_MENU, ATTACK_MENU,
    BUILDING_SOLDIERS_MENU, BUILDING_CONSTRUCTION_WINDOW, StartAttack, GET_XY_FOR_BUILD_BUILDING, WAITING_TO_RECIEVE_TYPE, WATING_ADDRESS;

}
